package com.chinadovey.parking.webapps.pojo.base;

public class CarLockTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.slave_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private String slaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.das_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private String dasId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.company_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private String companyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.bind_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private String bindNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.voltage
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Float voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.switch_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer switchStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.run_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer runStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.config_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer configStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.car_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer carStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.isauto
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private Integer isauto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock.remark
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.id
     *
     * @return the value of parking_car_lock.id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.id
     *
     * @param id the value for parking_car_lock.id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.slave_id
     *
     * @return the value of parking_car_lock.slave_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public String getSlaveId() {
        return slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.slave_id
     *
     * @param slaveId the value for parking_car_lock.slave_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setSlaveId(String slaveId) {
        this.slaveId = slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.das_id
     *
     * @return the value of parking_car_lock.das_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public String getDasId() {
        return dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.das_id
     *
     * @param dasId the value for parking_car_lock.das_id
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setDasId(String dasId) {
        this.dasId = dasId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.company_no
     *
     * @return the value of parking_car_lock.company_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public String getCompanyNo() {
        return companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.company_no
     *
     * @param companyNo the value for parking_car_lock.company_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setCompanyNo(String companyNo) {
        this.companyNo = companyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.bind_no
     *
     * @return the value of parking_car_lock.bind_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public String getBindNo() {
        return bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.bind_no
     *
     * @param bindNo the value for parking_car_lock.bind_no
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setBindNo(String bindNo) {
        this.bindNo = bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.voltage
     *
     * @return the value of parking_car_lock.voltage
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.voltage
     *
     * @param voltage the value for parking_car_lock.voltage
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setVoltage(Float voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.switch_status
     *
     * @return the value of parking_car_lock.switch_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getSwitchStatus() {
        return switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.switch_status
     *
     * @param switchStatus the value for parking_car_lock.switch_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setSwitchStatus(Integer switchStatus) {
        this.switchStatus = switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.run_status
     *
     * @return the value of parking_car_lock.run_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.run_status
     *
     * @param runStatus the value for parking_car_lock.run_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.config_status
     *
     * @return the value of parking_car_lock.config_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getConfigStatus() {
        return configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.config_status
     *
     * @param configStatus the value for parking_car_lock.config_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setConfigStatus(Integer configStatus) {
        this.configStatus = configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.car_status
     *
     * @return the value of parking_car_lock.car_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.car_status
     *
     * @param carStatus the value for parking_car_lock.car_status
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setCarStatus(Integer carStatus) {
        this.carStatus = carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.isauto
     *
     * @return the value of parking_car_lock.isauto
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public Integer getIsauto() {
        return isauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.isauto
     *
     * @param isauto the value for parking_car_lock.isauto
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setIsauto(Integer isauto) {
        this.isauto = isauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock.remark
     *
     * @return the value of parking_car_lock.remark
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock.remark
     *
     * @param remark the value for parking_car_lock.remark
     *
     * @mbggenerated Fri Sep 23 16:58:17 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}