package com.chinadovey.parking.webapps.pojo.base;

import java.util.Date;

public class IncomeCountBase{
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.value
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Double value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.start_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.end_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.type
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.park_id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Integer parkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.cash_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Double cashIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.online_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Double onlineIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_income_count_day.receivable
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    private Double receivable;

	private Double DisAmount;

	private Double FreeAmount;
	
	private int status;
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.id
     *
     * @return the value of parking_income_count_day.id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.id
     *
     * @param id the value for parking_income_count_day.id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.value
     *
     * @return the value of parking_income_count_day.value
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.value
     *
     * @param value the value for parking_income_count_day.value
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.start_time
     *
     * @return the value of parking_income_count_day.start_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.start_time
     *
     * @param startTime the value for parking_income_count_day.start_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.end_time
     *
     * @return the value of parking_income_count_day.end_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.end_time
     *
     * @param endTime the value for parking_income_count_day.end_time
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.type
     *
     * @return the value of parking_income_count_day.type
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.type
     *
     * @param type the value for parking_income_count_day.type
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.park_id
     *
     * @return the value of parking_income_count_day.park_id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.park_id
     *
     * @param parkId the value for parking_income_count_day.park_id
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.cash_income
     *
     * @return the value of parking_income_count_day.cash_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Double getCashIncome() {
        return cashIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.cash_income
     *
     * @param cashIncome the value for parking_income_count_day.cash_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setCashIncome(Double cashIncome) {
        this.cashIncome = cashIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.online_income
     *
     * @return the value of parking_income_count_day.online_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Double getOnlineIncome() {
        return onlineIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.online_income
     *
     * @param onlineIncome the value for parking_income_count_day.online_income
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setOnlineIncome(Double onlineIncome) {
        this.onlineIncome = onlineIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_income_count_day.receivable
     *
     * @return the value of parking_income_count_day.receivable
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public Double getReceivable() {
        return receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_income_count_day.receivable
     *
     * @param receivable the value for parking_income_count_day.receivable
     *
     * @mbggenerated Tue Jan 26 17:55:46 CST 2016
     */
    public void setReceivable(Double receivable) {
        this.receivable = receivable;
    }

	public Double getDisAmount() {
		return DisAmount;
	}

	public void setDisAmount(Double disAmount) {
		DisAmount = disAmount;
	}

	public Double getFreeAmount() {
		return FreeAmount;
	}

	public void setFreeAmount(Double freeAmount) {
		FreeAmount = freeAmount;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}
	
}