package com.chinadovey.parking.webapps.pojo.base;

import java.util.Date;

public class OperatorCarInOutCountBase {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.start_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.end_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.in_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Integer inTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.out_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Integer outTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.type
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.park_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private Integer parkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.operator_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_operator_car_in_out_count_month.operator
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    private String operator;
    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.id
     *
     * @return the value of parking_operator_car_in_out_count_month.id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.id
     *
     * @param id the value for parking_operator_car_in_out_count_month.id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.start_time
     *
     * @return the value of parking_operator_car_in_out_count_month.start_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.start_time
     *
     * @param startTime the value for parking_operator_car_in_out_count_month.start_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.end_time
     *
     * @return the value of parking_operator_car_in_out_count_month.end_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.end_time
     *
     * @param endTime the value for parking_operator_car_in_out_count_month.end_time
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.in_total
     *
     * @return the value of parking_operator_car_in_out_count_month.in_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Integer getInTotal() {
        return inTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.in_total
     *
     * @param inTotal the value for parking_operator_car_in_out_count_month.in_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setInTotal(Integer inTotal) {
        this.inTotal = inTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.out_total
     *
     * @return the value of parking_operator_car_in_out_count_month.out_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Integer getOutTotal() {
        return outTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.out_total
     *
     * @param outTotal the value for parking_operator_car_in_out_count_month.out_total
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setOutTotal(Integer outTotal) {
        this.outTotal = outTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.type
     *
     * @return the value of parking_operator_car_in_out_count_month.type
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.type
     *
     * @param type the value for parking_operator_car_in_out_count_month.type
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.park_id
     *
     * @return the value of parking_operator_car_in_out_count_month.park_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.park_id
     *
     * @param parkId the value for parking_operator_car_in_out_count_month.park_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.operator_id
     *
     * @return the value of parking_operator_car_in_out_count_month.operator_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.operator_id
     *
     * @param operatorId the value for parking_operator_car_in_out_count_month.operator_id
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_operator_car_in_out_count_month.operator
     *
     * @return the value of parking_operator_car_in_out_count_month.operator
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_operator_car_in_out_count_month.operator
     *
     * @param operator the value for parking_operator_car_in_out_count_month.operator
     *
     * @mbggenerated Tue Jan 26 14:06:54 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}