package com.chinadovey.parking.webapps.pojo;

import java.util.Date;

public class CarLockDataLocalCache {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.slave_id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private String slaveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.open_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer openState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.car_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer carState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.voltage
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Float voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.equi_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer equiState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.cycle
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.xh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.xl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer xl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.yh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer yh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.yl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer yl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.zh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer zh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.zl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Integer zl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.collect_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_lock_data_local_cache.save_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    private Date saveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.id
     *
     * @return the value of parking_car_lock_data_local_cache.id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.id
     *
     * @param id the value for parking_car_lock_data_local_cache.id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.slave_id
     *
     * @return the value of parking_car_lock_data_local_cache.slave_id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public String getSlaveId() {
        return slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.slave_id
     *
     * @param slaveId the value for parking_car_lock_data_local_cache.slave_id
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setSlaveId(String slaveId) {
        this.slaveId = slaveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.open_state
     *
     * @return the value of parking_car_lock_data_local_cache.open_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getOpenState() {
        return openState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.open_state
     *
     * @param openState the value for parking_car_lock_data_local_cache.open_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setOpenState(Integer openState) {
        this.openState = openState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.car_state
     *
     * @return the value of parking_car_lock_data_local_cache.car_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.car_state
     *
     * @param carState the value for parking_car_lock_data_local_cache.car_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setCarState(Integer carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.voltage
     *
     * @return the value of parking_car_lock_data_local_cache.voltage
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.voltage
     *
     * @param voltage the value for parking_car_lock_data_local_cache.voltage
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setVoltage(Float voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.equi_state
     *
     * @return the value of parking_car_lock_data_local_cache.equi_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getEquiState() {
        return equiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.equi_state
     *
     * @param equiState the value for parking_car_lock_data_local_cache.equi_state
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setEquiState(Integer equiState) {
        this.equiState = equiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.cycle
     *
     * @return the value of parking_car_lock_data_local_cache.cycle
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.cycle
     *
     * @param cycle the value for parking_car_lock_data_local_cache.cycle
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.xh
     *
     * @return the value of parking_car_lock_data_local_cache.xh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.xh
     *
     * @param xh the value for parking_car_lock_data_local_cache.xh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.xl
     *
     * @return the value of parking_car_lock_data_local_cache.xl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getXl() {
        return xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.xl
     *
     * @param xl the value for parking_car_lock_data_local_cache.xl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setXl(Integer xl) {
        this.xl = xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.yh
     *
     * @return the value of parking_car_lock_data_local_cache.yh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getYh() {
        return yh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.yh
     *
     * @param yh the value for parking_car_lock_data_local_cache.yh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setYh(Integer yh) {
        this.yh = yh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.yl
     *
     * @return the value of parking_car_lock_data_local_cache.yl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getYl() {
        return yl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.yl
     *
     * @param yl the value for parking_car_lock_data_local_cache.yl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setYl(Integer yl) {
        this.yl = yl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.zh
     *
     * @return the value of parking_car_lock_data_local_cache.zh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getZh() {
        return zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.zh
     *
     * @param zh the value for parking_car_lock_data_local_cache.zh
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setZh(Integer zh) {
        this.zh = zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.zl
     *
     * @return the value of parking_car_lock_data_local_cache.zl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Integer getZl() {
        return zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.zl
     *
     * @param zl the value for parking_car_lock_data_local_cache.zl
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setZl(Integer zl) {
        this.zl = zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.collect_time
     *
     * @return the value of parking_car_lock_data_local_cache.collect_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.collect_time
     *
     * @param collectTime the value for parking_car_lock_data_local_cache.collect_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_lock_data_local_cache.save_time
     *
     * @return the value of parking_car_lock_data_local_cache.save_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_lock_data_local_cache.save_time
     *
     * @param saveTime the value for parking_car_lock_data_local_cache.save_time
     *
     * @mbggenerated Tue Dec 20 18:23:29 CST 2016
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }
}