package com.chinadovey.parking.webapps.pojo;

public class CarUserRelCarNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.car_user_id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Integer carUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.car_no
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private String carNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.engine_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private String engineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.chassis_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private String chassisNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.parked_location
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private String parkedLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.latitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.longitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.status
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.type
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_car_user_rel_car_no.brand
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    private String brand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.id
     *
     * @return the value of parking_car_user_rel_car_no.id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.id
     *
     * @param id the value for parking_car_user_rel_car_no.id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.car_user_id
     *
     * @return the value of parking_car_user_rel_car_no.car_user_id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Integer getCarUserId() {
        return carUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.car_user_id
     *
     * @param carUserId the value for parking_car_user_rel_car_no.car_user_id
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setCarUserId(Integer carUserId) {
        this.carUserId = carUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.car_no
     *
     * @return the value of parking_car_user_rel_car_no.car_no
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.car_no
     *
     * @param carNo the value for parking_car_user_rel_car_no.car_no
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.engine_number
     *
     * @return the value of parking_car_user_rel_car_no.engine_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public String getEngineNumber() {
        return engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.engine_number
     *
     * @param engineNumber the value for parking_car_user_rel_car_no.engine_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setEngineNumber(String engineNumber) {
        this.engineNumber = engineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.chassis_number
     *
     * @return the value of parking_car_user_rel_car_no.chassis_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public String getChassisNumber() {
        return chassisNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.chassis_number
     *
     * @param chassisNumber the value for parking_car_user_rel_car_no.chassis_number
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setChassisNumber(String chassisNumber) {
        this.chassisNumber = chassisNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.parked_location
     *
     * @return the value of parking_car_user_rel_car_no.parked_location
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public String getParkedLocation() {
        return parkedLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.parked_location
     *
     * @param parkedLocation the value for parking_car_user_rel_car_no.parked_location
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setParkedLocation(String parkedLocation) {
        this.parkedLocation = parkedLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.latitude
     *
     * @return the value of parking_car_user_rel_car_no.latitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.latitude
     *
     * @param latitude the value for parking_car_user_rel_car_no.latitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.longitude
     *
     * @return the value of parking_car_user_rel_car_no.longitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.longitude
     *
     * @param longitude the value for parking_car_user_rel_car_no.longitude
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.status
     *
     * @return the value of parking_car_user_rel_car_no.status
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.status
     *
     * @param status the value for parking_car_user_rel_car_no.status
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.type
     *
     * @return the value of parking_car_user_rel_car_no.type
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.type
     *
     * @param type the value for parking_car_user_rel_car_no.type
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_car_user_rel_car_no.brand
     *
     * @return the value of parking_car_user_rel_car_no.brand
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_car_user_rel_car_no.brand
     *
     * @param brand the value for parking_car_user_rel_car_no.brand
     *
     * @mbggenerated Mon Apr 18 18:21:37 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }
}