package com.chinadovey.parking.webapps.pojo;

public class ChargingRules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.park_id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer parkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.no
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.name
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.car_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.rule_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.charge_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.free_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float freeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.cycle_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float cycleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.time_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Integer timeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String dayStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String dayEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String dayFirstTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float dayFirstTimePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float dayRemainTimePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float dayMaximumAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String nightStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String nightEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private String nightFirstTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float nightFirstTimePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float nightRemainTimePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float nightMaximumAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.allday_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float alldayMaximumAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.day_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float dayTimesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_charging_rules.night_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    private Float nightTimesPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.id
     *
     * @return the value of parking_charging_rules.id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.id
     *
     * @param id the value for parking_charging_rules.id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.park_id
     *
     * @return the value of parking_charging_rules.park_id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.park_id
     *
     * @param parkId the value for parking_charging_rules.park_id
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.no
     *
     * @return the value of parking_charging_rules.no
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.no
     *
     * @param no the value for parking_charging_rules.no
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.name
     *
     * @return the value of parking_charging_rules.name
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.name
     *
     * @param name the value for parking_charging_rules.name
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.car_type
     *
     * @return the value of parking_charging_rules.car_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.car_type
     *
     * @param carType the value for parking_charging_rules.car_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.rule_type
     *
     * @return the value of parking_charging_rules.rule_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.rule_type
     *
     * @param ruleType the value for parking_charging_rules.rule_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setRuleType(Integer ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.charge_type
     *
     * @return the value of parking_charging_rules.charge_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.charge_type
     *
     * @param chargeType the value for parking_charging_rules.charge_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.free_time
     *
     * @return the value of parking_charging_rules.free_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getFreeTime() {
        return freeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.free_time
     *
     * @param freeTime the value for parking_charging_rules.free_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setFreeTime(Float freeTime) {
        this.freeTime = freeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.cycle_time
     *
     * @return the value of parking_charging_rules.cycle_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getCycleTime() {
        return cycleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.cycle_time
     *
     * @param cycleTime the value for parking_charging_rules.cycle_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setCycleTime(Float cycleTime) {
        this.cycleTime = cycleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.time_type
     *
     * @return the value of parking_charging_rules.time_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Integer getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.time_type
     *
     * @param timeType the value for parking_charging_rules.time_type
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setTimeType(Integer timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_start_time
     *
     * @return the value of parking_charging_rules.day_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getDayStartTime() {
        return dayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_start_time
     *
     * @param dayStartTime the value for parking_charging_rules.day_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayStartTime(String dayStartTime) {
        this.dayStartTime = dayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_end_time
     *
     * @return the value of parking_charging_rules.day_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getDayEndTime() {
        return dayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_end_time
     *
     * @param dayEndTime the value for parking_charging_rules.day_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayEndTime(String dayEndTime) {
        this.dayEndTime = dayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_first_time
     *
     * @return the value of parking_charging_rules.day_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getDayFirstTime() {
        return dayFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_first_time
     *
     * @param dayFirstTime the value for parking_charging_rules.day_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayFirstTime(String dayFirstTime) {
        this.dayFirstTime = dayFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_first_time_price
     *
     * @return the value of parking_charging_rules.day_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getDayFirstTimePrice() {
        return dayFirstTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_first_time_price
     *
     * @param dayFirstTimePrice the value for parking_charging_rules.day_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayFirstTimePrice(Float dayFirstTimePrice) {
        this.dayFirstTimePrice = dayFirstTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_remain_time_price
     *
     * @return the value of parking_charging_rules.day_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getDayRemainTimePrice() {
        return dayRemainTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_remain_time_price
     *
     * @param dayRemainTimePrice the value for parking_charging_rules.day_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayRemainTimePrice(Float dayRemainTimePrice) {
        this.dayRemainTimePrice = dayRemainTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_maximum_amount
     *
     * @return the value of parking_charging_rules.day_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getDayMaximumAmount() {
        return dayMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_maximum_amount
     *
     * @param dayMaximumAmount the value for parking_charging_rules.day_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayMaximumAmount(Float dayMaximumAmount) {
        this.dayMaximumAmount = dayMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_start_time
     *
     * @return the value of parking_charging_rules.night_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getNightStartTime() {
        return nightStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_start_time
     *
     * @param nightStartTime the value for parking_charging_rules.night_start_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightStartTime(String nightStartTime) {
        this.nightStartTime = nightStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_end_time
     *
     * @return the value of parking_charging_rules.night_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getNightEndTime() {
        return nightEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_end_time
     *
     * @param nightEndTime the value for parking_charging_rules.night_end_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightEndTime(String nightEndTime) {
        this.nightEndTime = nightEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_first_time
     *
     * @return the value of parking_charging_rules.night_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public String getNightFirstTime() {
        return nightFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_first_time
     *
     * @param nightFirstTime the value for parking_charging_rules.night_first_time
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightFirstTime(String nightFirstTime) {
        this.nightFirstTime = nightFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_first_time_price
     *
     * @return the value of parking_charging_rules.night_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getNightFirstTimePrice() {
        return nightFirstTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_first_time_price
     *
     * @param nightFirstTimePrice the value for parking_charging_rules.night_first_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightFirstTimePrice(Float nightFirstTimePrice) {
        this.nightFirstTimePrice = nightFirstTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_remain_time_price
     *
     * @return the value of parking_charging_rules.night_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getNightRemainTimePrice() {
        return nightRemainTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_remain_time_price
     *
     * @param nightRemainTimePrice the value for parking_charging_rules.night_remain_time_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightRemainTimePrice(Float nightRemainTimePrice) {
        this.nightRemainTimePrice = nightRemainTimePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_maximum_amount
     *
     * @return the value of parking_charging_rules.night_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getNightMaximumAmount() {
        return nightMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_maximum_amount
     *
     * @param nightMaximumAmount the value for parking_charging_rules.night_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightMaximumAmount(Float nightMaximumAmount) {
        this.nightMaximumAmount = nightMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.allday_maximum_amount
     *
     * @return the value of parking_charging_rules.allday_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getAlldayMaximumAmount() {
        return alldayMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.allday_maximum_amount
     *
     * @param alldayMaximumAmount the value for parking_charging_rules.allday_maximum_amount
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setAlldayMaximumAmount(Float alldayMaximumAmount) {
        this.alldayMaximumAmount = alldayMaximumAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.day_times_price
     *
     * @return the value of parking_charging_rules.day_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getDayTimesPrice() {
        return dayTimesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.day_times_price
     *
     * @param dayTimesPrice the value for parking_charging_rules.day_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setDayTimesPrice(Float dayTimesPrice) {
        this.dayTimesPrice = dayTimesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_charging_rules.night_times_price
     *
     * @return the value of parking_charging_rules.night_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public Float getNightTimesPrice() {
        return nightTimesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_charging_rules.night_times_price
     *
     * @param nightTimesPrice the value for parking_charging_rules.night_times_price
     *
     * @mbggenerated Thu Mar 31 18:52:25 CST 2016
     */
    public void setNightTimesPrice(Float nightTimesPrice) {
        this.nightTimesPrice = nightTimesPrice;
    }
}