package com.chinadovey.parking.webapps.pojo;

import java.util.ArrayList;
import java.util.List;

public class DasConnectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public DasConnectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDasIdIsNull() {
            addCriterion("das_id is null");
            return (Criteria) this;
        }

        public Criteria andDasIdIsNotNull() {
            addCriterion("das_id is not null");
            return (Criteria) this;
        }

        public Criteria andDasIdEqualTo(String value) {
            addCriterion("das_id =", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotEqualTo(String value) {
            addCriterion("das_id <>", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdGreaterThan(String value) {
            addCriterion("das_id >", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdGreaterThanOrEqualTo(String value) {
            addCriterion("das_id >=", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLessThan(String value) {
            addCriterion("das_id <", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLessThanOrEqualTo(String value) {
            addCriterion("das_id <=", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdLike(String value) {
            addCriterion("das_id like", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotLike(String value) {
            addCriterion("das_id not like", value, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdIn(List<String> values) {
            addCriterion("das_id in", values, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotIn(List<String> values) {
            addCriterion("das_id not in", values, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdBetween(String value1, String value2) {
            addCriterion("das_id between", value1, value2, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasIdNotBetween(String value1, String value2) {
            addCriterion("das_id not between", value1, value2, "dasId");
            return (Criteria) this;
        }

        public Criteria andDasVersionIsNull() {
            addCriterion("das_version is null");
            return (Criteria) this;
        }

        public Criteria andDasVersionIsNotNull() {
            addCriterion("das_version is not null");
            return (Criteria) this;
        }

        public Criteria andDasVersionEqualTo(String value) {
            addCriterion("das_version =", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionNotEqualTo(String value) {
            addCriterion("das_version <>", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionGreaterThan(String value) {
            addCriterion("das_version >", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionGreaterThanOrEqualTo(String value) {
            addCriterion("das_version >=", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionLessThan(String value) {
            addCriterion("das_version <", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionLessThanOrEqualTo(String value) {
            addCriterion("das_version <=", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionLike(String value) {
            addCriterion("das_version like", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionNotLike(String value) {
            addCriterion("das_version not like", value, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionIn(List<String> values) {
            addCriterion("das_version in", values, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionNotIn(List<String> values) {
            addCriterion("das_version not in", values, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionBetween(String value1, String value2) {
            addCriterion("das_version between", value1, value2, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andDasVersionNotBetween(String value1, String value2) {
            addCriterion("das_version not between", value1, value2, "dasVersion");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("session_id is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("session_id is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(Long value) {
            addCriterion("session_id =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(Long value) {
            addCriterion("session_id <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(Long value) {
            addCriterion("session_id >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("session_id >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(Long value) {
            addCriterion("session_id <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(Long value) {
            addCriterion("session_id <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<Long> values) {
            addCriterion("session_id in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<Long> values) {
            addCriterion("session_id not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(Long value1, Long value2) {
            addCriterion("session_id between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(Long value1, Long value2) {
            addCriterion("session_id not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andServerAddressIsNull() {
            addCriterion("server_address is null");
            return (Criteria) this;
        }

        public Criteria andServerAddressIsNotNull() {
            addCriterion("server_address is not null");
            return (Criteria) this;
        }

        public Criteria andServerAddressEqualTo(String value) {
            addCriterion("server_address =", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressNotEqualTo(String value) {
            addCriterion("server_address <>", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressGreaterThan(String value) {
            addCriterion("server_address >", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressGreaterThanOrEqualTo(String value) {
            addCriterion("server_address >=", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressLessThan(String value) {
            addCriterion("server_address <", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressLessThanOrEqualTo(String value) {
            addCriterion("server_address <=", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressLike(String value) {
            addCriterion("server_address like", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressNotLike(String value) {
            addCriterion("server_address not like", value, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressIn(List<String> values) {
            addCriterion("server_address in", values, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressNotIn(List<String> values) {
            addCriterion("server_address not in", values, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressBetween(String value1, String value2) {
            addCriterion("server_address between", value1, value2, "serverAddress");
            return (Criteria) this;
        }

        public Criteria andServerAddressNotBetween(String value1, String value2) {
            addCriterion("server_address not between", value1, value2, "serverAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_das_connect
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 17 14:51:12 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parking_das_connect
     *
     * @mbggenerated Mon Jul 17 14:51:12 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}