package com.chinadovey.parking.webapps.pojo;

public class Park {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.code
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.name
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.linkman
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.tel
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.email
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.address
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.latitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.longitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.price
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.picture
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.total
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer total;//li 用于存放车位数量

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.empty
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer empty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.company_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.closing_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String closingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.opening_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String openingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.is_free
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer isFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.park_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer parkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.charging_rules_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer chargingRulesId;
    private Integer emptybase;
    //非数据库字段
    private String companyName;
    

    public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public Integer getEmptybase() {
		return emptybase;
	}

	public void setEmptybase(Integer emptybase) {
		this.emptybase = emptybase;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.secret_key
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_park.interface_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    private Integer interfaceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.id
     *
     * @return the value of parking_park.id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.id
     *
     * @param id the value for parking_park.id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.code
     *
     * @return the value of parking_park.code
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.code
     *
     * @param code the value for parking_park.code
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.name
     *
     * @return the value of parking_park.name
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.name
     *
     * @param name the value for parking_park.name
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.type
     *
     * @return the value of parking_park.type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.type
     *
     * @param type the value for parking_park.type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.linkman
     *
     * @return the value of parking_park.linkman
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.linkman
     *
     * @param linkman the value for parking_park.linkman
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.tel
     *
     * @return the value of parking_park.tel
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.tel
     *
     * @param tel the value for parking_park.tel
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.email
     *
     * @return the value of parking_park.email
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.email
     *
     * @param email the value for parking_park.email
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.address
     *
     * @return the value of parking_park.address
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.address
     *
     * @param address the value for parking_park.address
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.latitude
     *
     * @return the value of parking_park.latitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.latitude
     *
     * @param latitude the value for parking_park.latitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.longitude
     *
     * @return the value of parking_park.longitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.longitude
     *
     * @param longitude the value for parking_park.longitude
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.price
     *
     * @return the value of parking_park.price
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.price
     *
     * @param price the value for parking_park.price
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.picture
     *
     * @return the value of parking_park.picture
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.picture
     *
     * @param picture the value for parking_park.picture
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.total
     *
     * @return the value of parking_park.total
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.total
     *
     * @param total the value for parking_park.total
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.empty
     *
     * @return the value of parking_park.empty
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getEmpty() {
        return empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.empty
     *
     * @param empty the value for parking_park.empty
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setEmpty(Integer empty) {
        this.empty = empty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.company_id
     *
     * @return the value of parking_park.company_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.company_id
     *
     * @param companyId the value for parking_park.company_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.closing_time
     *
     * @return the value of parking_park.closing_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getClosingTime() {
        return closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.closing_time
     *
     * @param closingTime the value for parking_park.closing_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setClosingTime(String closingTime) {
        this.closingTime = closingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.opening_time
     *
     * @return the value of parking_park.opening_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.opening_time
     *
     * @param openingTime the value for parking_park.opening_time
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setOpeningTime(String openingTime) {
        this.openingTime = openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.is_free
     *
     * @return the value of parking_park.is_free
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.is_free
     *
     * @param isFree the value for parking_park.is_free
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setIsFree(Integer isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.park_type
     *
     * @return the value of parking_park.park_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getParkType() {
        return parkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.park_type
     *
     * @param parkType the value for parking_park.park_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setParkType(Integer parkType) {
        this.parkType = parkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.charging_rules_id
     *
     * @return the value of parking_park.charging_rules_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getChargingRulesId() {
        return chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.charging_rules_id
     *
     * @param chargingRulesId the value for parking_park.charging_rules_id
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setChargingRulesId(Integer chargingRulesId) {
        this.chargingRulesId = chargingRulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.secret_key
     *
     * @return the value of parking_park.secret_key
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.secret_key
     *
     * @param secretKey the value for parking_park.secret_key
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_park.interface_type
     *
     * @return the value of parking_park.interface_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public Integer getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_park.interface_type
     *
     * @param interfaceType the value for parking_park.interface_type
     *
     * @mbggenerated Sun Jul 03 16:02:39 CST 2016
     */
    public void setInterfaceType(Integer interfaceType) {
        this.interfaceType = interfaceType;
    }
}