package com.chinadovey.parking.webapps.pojo;

public class Pp_Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_goods.id
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_goods.gname
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    private String gname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_goods.price
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_goods.kinds
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    private String kinds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_goods.id
     *
     * @return the value of pp_goods.id
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_goods.id
     *
     * @param id the value for pp_goods.id
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_goods.gname
     *
     * @return the value of pp_goods.gname
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_goods.gname
     *
     * @param gname the value for pp_goods.gname
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_goods.price
     *
     * @return the value of pp_goods.price
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_goods.price
     *
     * @param price the value for pp_goods.price
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_goods.kinds
     *
     * @return the value of pp_goods.kinds
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public String getKinds() {
        return kinds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_goods.kinds
     *
     * @param kinds the value for pp_goods.kinds
     *
     * @mbggenerated Fri Oct 13 13:45:15 CST 2017
     */
    public void setKinds(String kinds) {
        this.kinds = kinds;
    }
}