package com.chinadovey.parking.webapps.pojo;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_id
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_name
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_age
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    private Integer teacherAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_id
     *
     * @return the value of teacher.teacher_id
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_id
     *
     * @param teacherId the value for teacher.teacher_id
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_name
     *
     * @return the value of teacher.teacher_name
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_name
     *
     * @param teacherName the value for teacher.teacher_name
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_age
     *
     * @return the value of teacher.teacher_age
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public Integer getTeacherAge() {
        return teacherAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_age
     *
     * @param teacherAge the value for teacher.teacher_age
     *
     * @mbggenerated Fri Aug 11 16:34:16 CST 2017
     */
    public void setTeacherAge(Integer teacherAge) {
        this.teacherAge = teacherAge;
    }
}