package com.chinadovey.parking.webapps.pojo;

import com.chinadovey.parking.webapps.pojo.base.UiMenuBase;


public class UiMenu extends UiMenuBase{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_NAME
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_DESC
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_ACTION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_RESOURCE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_OPERATION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_PARENT_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuParentGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_TREE_PATH
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuTreePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_ORDER
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_IS_ENABLE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private Boolean menuIsEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column municipal_ui_menu.MENU_ICON
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    private String menuIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_GUID
     *
     * @return the value of municipal_ui_menu.MENU_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuGuid() {
        return menuGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_GUID
     *
     * @param menuGuid the value for municipal_ui_menu.MENU_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuGuid(String menuGuid) {
        this.menuGuid = menuGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_NAME
     *
     * @return the value of municipal_ui_menu.MENU_NAME
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_NAME
     *
     * @param menuName the value for municipal_ui_menu.MENU_NAME
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_DESC
     *
     * @return the value of municipal_ui_menu.MENU_DESC
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_DESC
     *
     * @param menuDesc the value for municipal_ui_menu.MENU_DESC
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_ACTION
     *
     * @return the value of municipal_ui_menu.MENU_ACTION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuAction() {
        return menuAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_ACTION
     *
     * @param menuAction the value for municipal_ui_menu.MENU_ACTION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuAction(String menuAction) {
        this.menuAction = menuAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_RESOURCE
     *
     * @return the value of municipal_ui_menu.MENU_RESOURCE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuResource() {
        return menuResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_RESOURCE
     *
     * @param menuResource the value for municipal_ui_menu.MENU_RESOURCE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuResource(String menuResource) {
        this.menuResource = menuResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_OPERATION
     *
     * @return the value of municipal_ui_menu.MENU_OPERATION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuOperation() {
        return menuOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_OPERATION
     *
     * @param menuOperation the value for municipal_ui_menu.MENU_OPERATION
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuOperation(String menuOperation) {
        this.menuOperation = menuOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_PARENT_GUID
     *
     * @return the value of municipal_ui_menu.MENU_PARENT_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuParentGuid() {
        return menuParentGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_PARENT_GUID
     *
     * @param menuParentGuid the value for municipal_ui_menu.MENU_PARENT_GUID
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuParentGuid(String menuParentGuid) {
        this.menuParentGuid = menuParentGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_TREE_PATH
     *
     * @return the value of municipal_ui_menu.MENU_TREE_PATH
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuTreePath() {
        return menuTreePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_TREE_PATH
     *
     * @param menuTreePath the value for municipal_ui_menu.MENU_TREE_PATH
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuTreePath(String menuTreePath) {
        this.menuTreePath = menuTreePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_ORDER
     *
     * @return the value of municipal_ui_menu.MENU_ORDER
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_ORDER
     *
     * @param menuOrder the value for municipal_ui_menu.MENU_ORDER
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_IS_ENABLE
     *
     * @return the value of municipal_ui_menu.MENU_IS_ENABLE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public Boolean getMenuIsEnable() {
        return menuIsEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_IS_ENABLE
     *
     * @param menuIsEnable the value for municipal_ui_menu.MENU_IS_ENABLE
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuIsEnable(Boolean menuIsEnable) {
        this.menuIsEnable = menuIsEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column municipal_ui_menu.MENU_ICON
     *
     * @return the value of municipal_ui_menu.MENU_ICON
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column municipal_ui_menu.MENU_ICON
     *
     * @param menuIcon the value for municipal_ui_menu.MENU_ICON
     *
     * @mbggenerated Sun Feb 15 13:55:37 CST 2015
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }
}