package com.chinadovey.parking.webapps.pojo;

import java.util.Date;

import com.chinadovey.parking.webapps.pojo.base.UserBase;

public class User extends UserBase{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.name
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.password
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.realname
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.email
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.tel
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.create_user_id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private Integer createUserId;
    
    private Integer companyId;
    

    public Integer getCompanyId() {
		return companyId;
	}
    public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
    //闈炴暟鎹簱瀛楁
    private String roleName;
    private String parkName;
    private String comName;
    private String[] parkIds;
    
	public String[] getParkIds() {
		return parkIds;
	}
	public void setParkIds(String[] parkIds) {
		this.parkIds = parkIds;
	}
	public String getComName() {
		return comName;
	}
	public void setComName(String comName) {
		this.comName = comName;
	}
	public String getParkName() {
		return parkName;
	}
	public void setParkName(String parkName) {
		this.parkName = parkName;
	}
	public String getRoleName() {
		return roleName;
	}
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.create_time
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user.picture
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.id
     *
     * @return the value of parking_user.id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.id
     *
     * @param id the value for parking_user.id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.name
     *
     * @return the value of parking_user.name
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.name
     *
     * @param name the value for parking_user.name
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.password
     *
     * @return the value of parking_user.password
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.password
     *
     * @param password the value for parking_user.password
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.realname
     *
     * @return the value of parking_user.realname
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.realname
     *
     * @param realname the value for parking_user.realname
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.email
     *
     * @return the value of parking_user.email
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.email
     *
     * @param email the value for parking_user.email
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.tel
     *
     * @return the value of parking_user.tel
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.tel
     *
     * @param tel the value for parking_user.tel
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.create_user_id
     *
     * @return the value of parking_user.create_user_id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.create_user_id
     *
     * @param createUserId the value for parking_user.create_user_id
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.create_time
     *
     * @return the value of parking_user.create_time
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.create_time
     *
     * @param createTime the value for parking_user.create_time
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user.picture
     *
     * @return the value of parking_user.picture
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user.picture
     *
     * @param picture the value for parking_user.picture
     *
     * @mbggenerated Thu Nov 12 10:12:37 CST 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }
}