package com.chinadovey.parking.webapps.pojo;

public class UserRelBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user_rel_business.business_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user_rel_business.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user_rel_business.business_id
     *
     * @return the value of parking_user_rel_business.business_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user_rel_business.business_id
     *
     * @param businessId the value for parking_user_rel_business.business_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user_rel_business.user_id
     *
     * @return the value of parking_user_rel_business.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user_rel_business.user_id
     *
     * @param userId the value for parking_user_rel_business.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}