package com.chinadovey.parking.webapps.pojo;

public class UserRelCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user_rel_company.company_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking_user_rel_company.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user_rel_company.company_id
     *
     * @return the value of parking_user_rel_company.company_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user_rel_company.company_id
     *
     * @param companyId the value for parking_user_rel_company.company_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking_user_rel_company.user_id
     *
     * @return the value of parking_user_rel_company.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking_user_rel_company.user_id
     *
     * @param userId the value for parking_user_rel_company.user_id
     *
     * @mbggenerated Tue Apr 19 13:51:03 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}