package com.chinadovey.parking.webapps.pojo.local;

import java.math.BigDecimal;
import java.util.Date;

public class OrderCarInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.PKID
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private Long pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.OrderNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.CarNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private String carno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.DriverName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private String drivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.MobilePhone
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.OrderSource
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private BigDecimal ordersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.UserName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.ArrialTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private Date arrialtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.OrderTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderCarInfo.Remark
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    private Object remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.PKID
     *
     * @return the value of OrderCarInfo.PKID
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.PKID
     *
     * @param pkid the value for OrderCarInfo.PKID
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.OrderNO
     *
     * @return the value of OrderCarInfo.OrderNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.OrderNO
     *
     * @param orderno the value for OrderCarInfo.OrderNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.CarNO
     *
     * @return the value of OrderCarInfo.CarNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public String getCarno() {
        return carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.CarNO
     *
     * @param carno the value for OrderCarInfo.CarNO
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setCarno(String carno) {
        this.carno = carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.DriverName
     *
     * @return the value of OrderCarInfo.DriverName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public String getDrivername() {
        return drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.DriverName
     *
     * @param drivername the value for OrderCarInfo.DriverName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.MobilePhone
     *
     * @return the value of OrderCarInfo.MobilePhone
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.MobilePhone
     *
     * @param mobilephone the value for OrderCarInfo.MobilePhone
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.OrderSource
     *
     * @return the value of OrderCarInfo.OrderSource
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public BigDecimal getOrdersource() {
        return ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.OrderSource
     *
     * @param ordersource the value for OrderCarInfo.OrderSource
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setOrdersource(BigDecimal ordersource) {
        this.ordersource = ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.UserName
     *
     * @return the value of OrderCarInfo.UserName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.UserName
     *
     * @param username the value for OrderCarInfo.UserName
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.ArrialTime
     *
     * @return the value of OrderCarInfo.ArrialTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public Date getArrialtime() {
        return arrialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.ArrialTime
     *
     * @param arrialtime the value for OrderCarInfo.ArrialTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setArrialtime(Date arrialtime) {
        this.arrialtime = arrialtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.OrderTime
     *
     * @return the value of OrderCarInfo.OrderTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.OrderTime
     *
     * @param ordertime the value for OrderCarInfo.OrderTime
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderCarInfo.Remark
     *
     * @return the value of OrderCarInfo.Remark
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public Object getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderCarInfo.Remark
     *
     * @param remark the value for OrderCarInfo.Remark
     *
     * @mbggenerated Thu Oct 15 13:10:28 CST 2015
     */
    public void setRemark(Object remark) {
        this.remark = remark;
    }
}